### PR TITLE
Add documentation for enabling HTTPS

### PR DESCRIPTION
**Pull request by jjlin**

### CODE REVIEW

**Comment by jjlin** [comment]
Any particular issues with this PR, or you just need more time to look it over?

**Comment by sickill** [comment]
Hey! Just haven't had time to look at it sorry! But will do shortly (just quickly scrolled through the changes and it looks great).

**Comment by jjlin** [comment]
Ah, okay, just wondering. Feel free to take your time, thanks.

**Comment by sickill** [comment]
Btw, I've modified docker-compose to use explicit separate nginx container and removed the baked-in nginx and supervisord from the Dockerfile. It should be now easier to improve https setup, for example with something like [nginx-proxy](https://github.com/jwilder/nginx-proxy) + [docker-letsencrypt-nginx-proxy-companion
](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)

**Pull request merged**
