### PR TITLE
Add tip for recursive submodule

### PR DESCRIPTION
**Pull request by jrschumacher**
Add tip for those (like me) who didn't run recursive on clone

### CODE REVIEW

**Comment by sickill** [comment]
Thanks! What about a small tweak, to make it more specific about the `--recursive` switch?
For example:

"If you already cloned without `--recursive` switch then run `git submodule update --recursive --remote --init`."

Btw, what does `--remote` do?

**Comment by jrschumacher** [comment]
@sickill please ignore this, for now, it didn't do what was intended.

**Comment by sickill** [comment]
@jrschumacher ok, no prob! ;)

**Comment by sickill** [comment]
Feel free to close it and open a new one if you think it makes sense (or don't open if it doesn't ;-).

**Pull request closed without merging**
