### PR TITLE
robots loves twitter cards

### PR DESCRIPTION
**Pull request by mathieu-aubin**
Allows twitterbot access to the images files so tweets containing asciicasts and/or based on asciicasts will fully render as a twitter card instead of lacking the image preview

related to this [forum mention](https://discourse.asciinema.org/t/robots-txt-blocks-images/64)

### CODE REVIEW

**Comment by sickill** [comment]
Wonderful, thanks!

**Comment by sickill** [comment]
Hmm, card validator still says this:

```
INFO:  Page fetched successfully
INFO:  18 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully
WARN:  The image URL https://asciinema.org/a/112367.png specified by the 'twitter:image' metatag may be restricted by the site's robots.txt file, which will prevent Twitter from fetching it.
WARN:  this card is redirected to https://asciinema.org/a/112367
```

Not sure, but maybe the order of entries matters in robots.txt?

**Comment by sickill** [comment]
I think this may be it. This example has the catch-all (`*`) entry as the last one actually: http://www.robotstxt.org/faq/robotstxt.html

**Comment by sickill** [comment]
Ok, it works 👍 . The order doesn't matter. It was probably caching issue on verifier side.

**Comment by mathieu-aubin** [comment]
I also had removed the link to the robotstxt website as its dead (still in the live version)
http://www.robotstxt.org/wc/norobots.html

And yes, its must have been cached

**Comment by sickill** [comment]
Ah, yes, I copied this addition to a copy of robots.txt I have on asciinema.org (I have custom nginx there for rate limiting / bad bot blocking purposes). 

Thanks for help 👌

**Comment by mathieu-aubin** [comment]
If you get tons of traffic and want to get rid of a disk read each time robots.txt gets called, you can have nginx output it upon request. Probably doesn't apply so much to servers running only one websites but i run multiple server that in turn have multiple domains (300+ each) and saving on hdd reads is always a good thing, even running expensive nvme drives.

This is just an example, of course it would need to be modified to fit your robots.txt

    location = /robots.txt {
      default_type "text/plain";
      expires max; access_log off;
      return 200 "User-agent: *\nDisallow: /\n\nHost: $scheme://$server_name\n";
    }

If you want/need some help with anything nginx-related, feel free to email me [asciinema user OldFart](https://asciinema.org/~OldFart) -- i'm assuming you have access to emails from the profiles...

**Comment by sickill** [comment]
Thanks @mathieu-aubin. Didn't know you can inline a file like that. That will definitely come handy 👍

**Pull request merged**
